ai_project:
  target: dev
  outputs: 
    dev: 
      type: clickhouse
      threads: 8
      host: 127.0.0.1
      port: 8123
      user: root
      password: root
      database: dev_ai_analytics
      schema: dev_ai_analytics

    prod:
      type: clickhouse
      threads: 4
      host: 127.0.0.1
      port: 8123
      user: root
      password: root
      database: ai_analytics
      schema: ai_analytics