ai_project:
  target: dev
  outputs: 
    dev: 
      type: clickhouse
      threads: 4
      host: 167.235.62.53
      port: 8123
      user: default
      password: admin
      database: dev_ai_analytics
      schema: dev_ai_analytics

    prod:
      type: clickhouse
      threads: 4
      host: 167.235.62.53
      port: 8123
      user: default
      password: admin
      database: ai_analytics
      schema: ai_analytics